default: 
 adapter: mysql2
 pool: 5
 timeout: 5000
development:  
  adapter: mysql2
  database : myriander_test
  encoding: utf8
  pool: 5
  username: root 
  host: localhost
production: 
 adapter: mysql2
 database: "<%= Rails.application.secrets.database_name %>"
 password: "<%= Rails.application.secrets.database_password %>"
 pool: 5
 timeout: 5000
 username: "<%= Rails.application.secrets.database_username %>"
test: 
 adapter: mysql2
 database: myriander_test
 password: ""
 pool: 5
 timeout: 5000
 username: root
