# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # secret_key_base:      19e4b9a619418e2ea9d554ef4bdd064821c529b9eaf615bc030316e7f572387ecfa63baf7fcc8b53d45d4323de229d99991515350f3ec482156a7c04ea9c93e7
 secret_key_base: ee50b22142e976723e247160b7f2a3a2f4c58f6ac5b70627c6c4b4b33df09d8ef16412d19909b14adc960ef67ba5ed302dafe75134df0421cf27f8f1145f07be 
 secret_token: ddfddc39ed75781e8d132adbab7bcf6558e14d54fab62e9d9f6bdf5ecd07f6d17d5f9756bccdae2ca803d7c6b31557190bb2d3c9fd15df29799635466e5019a
 smtp_user_name:       <%= ENV["SMTP_USER_NAME"] %>
  smtp_password:        <%= ENV["SMTP_PASSWORD"] %>
  fractel_endpoint:     <%= ENV["FRACTEL_ENDPOINT"] %>
  fractel_username:     <%= ENV["FRACTEL_USERNAME"] %>
  fractel_password:     <%= ENV["FRACTEL_PASSWORD"] %>
  stripe_public_key:    <%= ENV["STRIPE_PUBLIC_KEY"] %>
  stripe_secret_key:    <%= ENV["STRIPE_SECRET_KEY"] %>
  

test:
  secret_key_base: 92bb2a651c96e44e92b5d5aa49de55f99b4297eaf9c496f7076e4091f9921954a4449fb438be27c328c51bf370af6c08c3172444e1f9faf1eb2d86fa9a011c9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:      <%= ENV["MYR_SECRET_KEY_BASE"] %>
  database_name:        <%= ENV["MYR_DATABASE"] %>
  database_username:    <%= ENV["MYR_USERNAME"] %>
  database_password:    <%= ENV["MYR_PASSWORD"] %>
  smtp_user_name:       <%= ENV["SMTP_USER_NAME"] %>
  smtp_password:        <%= ENV["SMTP_PASSWORD"] %>
  fractel_endpoint:     <%= ENV["FRACTEL_ENDPOINT"] %>
  fractel_username:     <%= ENV["FRACTEL_USERNAME"] %>
  fractel_password:     <%= ENV["FRACTEL_PASSWORD"] %>
  stripe_public_key:    <%= ENV["STRIPE_PUBLIC_KEY"] %>
  stripe_secret_key:    <%= ENV["STRIPE_SECRET_KEY"] %>
